export interface BlogPost {
  slug: string;
  title: string;
  excerpt: string;
  category: string;
  author: string;
  publishedDate: string;
  readTimeMinutes: number;
  tags: string[];
  coverImage?: string;
  relatedToolId: string;
  content: {
    sectionId: string;
    heading: string;
    body: string;
  }[];
  faqs?: { question: string; answer: string }[];
}

export const BLOG_POSTS: BlogPost[] = [
  {
    slug: 'how-to-calculate-cgpa',
    title: 'How to Calculate GPA, SGPA & CGPA: The Complete Student Guide',
    excerpt: 'Understand semester credit weighting, letter grade point conversions (4.0 vs 10.0 scale), and exact formulas to calculate and target your cumulative CGPA.',
    category: 'Study Tips',
    author: 'Academic Advisory Team',
    publishedDate: 'January 2026',
    readTimeMinutes: 5,
    tags: ['CGPA', 'GPA', 'Grades', 'University', 'College', 'Calculators'],
    relatedToolId: 'gpa-cgpa-calculator',
    content: [
      {
        sectionId: 'understanding-gpa',
        heading: '1. What is the Difference Between SGPA and CGPA?',
        body: 'SGPA (Semester Grade Point Average) measures your academic achievement in a single term or semester, while CGPA (Cumulative Grade Point Average) represents the overall weighted average of all semesters completed throughout your degree program.',
      },
      {
        sectionId: 'formula',
        heading: '2. The Weighted Grade Point Formula',
        body: 'To calculate your SGPA:\n1. Multiply the grade points earned in each course by the course credit hours.\n2. Sum these credit-point products across all courses in the term.\n3. Divide the total credit points by the total registered credits in the semester.\n\nFormula:\nSGPA = (Sum of [Grade Points × Credit Hours]) / (Total Credit Hours)',
      },
      {
        sectionId: 'target-planning',
        heading: '3. How to Set Grade Targets for Upcoming Semesters',
        body: 'If you need to raise your CGPA to meet scholarship or graduate school requirements (e.g. from 3.4 to 3.75), calculate your required SGPA by weighting past semesters against the remaining credit hours.',
      },
    ],
    faqs: [
      { question: 'Is a 3.8 GPA on a 4.0 scale considered honors?', answer: 'Yes, at most universities a GPA of 3.75 to 4.0 qualifies for Magna Cum Laude or Summa Cum Laude distinction.' },
      { question: 'How do credit hours affect overall CGPA?', answer: 'Higher credit courses (e.g. 4-credit lab courses) exert significantly greater mathematical influence on your CGPA than 1 or 2-credit electives.' },
    ],
  },
  {
    slug: 'how-to-make-ats-friendly-resume',
    title: 'How to Build an ATS-Compliant Student Resume in 2026',
    excerpt: 'Step-by-step blueprint for formatting clean, recruiter-friendly resumes that pass Applicant Tracking Systems with quantifiable project bullets.',
    category: 'Career & Resumes',
    author: 'Career Studio & Recruiters',
    publishedDate: 'February 2026',
    readTimeMinutes: 6,
    tags: ['Resume', 'Career', 'ATS', 'Internships', 'Jobs', 'Interview'],
    relatedToolId: 'resume-builder',
    content: [
      {
        sectionId: 'what-is-ats',
        heading: '1. Why Do Applicant Tracking Systems Reject Resumes?',
        body: 'Modern corporate applicant tracking systems (like Workday, Taleo, and Greenhouse) parse resumes into structured text fields. Complex graphical columns, tables, headers/footers, and non-standard fonts cause parse errors that obscure your qualifications.',
      },
      {
        sectionId: 'action-formula',
        heading: '2. The Google XYZ Action Bullet Formula',
        body: 'Never write vague job responsibilities. Use the proven formula: "Accomplished [X] as measured by [Y], by doing [Z]".\n\nExample:\n• Poor: "Worked on website speed."\n• Strong: "Optimized React frontend bundle size by 38% using Vite code-splitting, reducing page load latency for 50,000+ monthly users."',
      },
      {
        sectionId: 'skills-hierarchy',
        heading: '3. Organizing Technical Skills and Projects',
        body: 'Group technical skills into clear categories: Languages, Frameworks, Developer Tools, and Cloud Platforms. Highlight production deployments with clickable GitHub repositories or live URLs.',
      },
    ],
    faqs: [
      { question: 'Should student resumes be strictly one page?', answer: 'Yes, undergraduate and early-career resumes should strictly fit on one clean standard page (A4 or US Letter).' },
      { question: 'Is PDF better than Word for ATS?', answer: 'Clean text-layer PDFs generated by standard print engines preserve styling while parsing identically to text documents.' },
    ],
  },
  {
    slug: 'how-to-compress-pdf-without-losing-quality',
    title: 'How to Compress & Optimize PDF Files for Online Submissions',
    excerpt: 'Learn how to compress lecture slides, research papers, and assignment PDFs to exact file size limits (under 2 MB, 500 KB, or 200 KB) without blur.',
    category: 'How-To Guides',
    author: 'STUDKIT Technical Team',
    publishedDate: 'January 2026',
    readTimeMinutes: 4,
    tags: ['PDF', 'Compress', 'Merge', 'Document', 'Uploads'],
    relatedToolId: 'pdf-merger',
    content: [
      {
        sectionId: 'why-compress',
        heading: '1. Overcoming Portal File Size Limits',
        body: 'University submission portals and government exam registration forms frequently enforce strict file upload ceilings (e.g. 500 KB or 1 MB). Scanned PDF documents often contain uncompressed high-resolution images that balloon file sizes needlessly.',
      },
      {
        sectionId: 'optimization-process',
        heading: '2. Client-Side PDF Re-encoding',
        body: 'By downsampling embedded color images to 150 DPI and removing redundant font tables or unreferenced metadata, PDF sizes can be reduced by 60% to 80% with zero noticeable degradation on desktop screens or printouts.',
      },
    ],
    faqs: [
      { question: 'Is my document uploaded to a public cloud when compressing on STUDKIT?', answer: 'No. STUDKIT processes PDFs directly within your local browser memory using client-side JavaScript, ensuring 100% privacy.' },
    ],
  },
  {
    slug: 'how-to-study-effectively-with-ai',
    title: 'How to Turn Lecture Notes & Documents into Active Recall Flashcards',
    excerpt: 'Master active recall and spaced repetition by generating grounded multiple-choice questions and flashcard decks from syllabus textbooks.',
    category: 'AI for Students',
    author: 'Cognitive Science Lab',
    publishedDate: 'February 2026',
    readTimeMinutes: 6,
    tags: ['AI', 'Flashcards', 'MCQs', 'Active Recall', 'Study Tips', 'Revision'],
    relatedToolId: 'ai-document-mcq',
    content: [
      {
        sectionId: 'active-recall',
        heading: '1. Why Passive Rereading Fails',
        body: 'Cognitive psychology research proves that passively rereading textbook highlights produces the "illusion of competence." Active retrieval—forcing your brain to recall definitions, formulas, and concepts—strengthens neural pathways significantly faster.',
      },
      {
        sectionId: 'grounded-mcqs',
        heading: '2. Generating Grounded Self-Assessment Questions',
        body: 'Upload your lecture PDF or slide deck to extract verifiable multiple-choice questions with answer explanations. Always verify that questions reference specific paragraphs from your assigned readings.',
      },
    ],
    faqs: [
      { question: 'How many flashcards should I review per day?', answer: 'Reviewing 20 to 40 flashcards daily using spaced intervals yields higher retention than cramming 200 cards the night before an exam.' },
    ],
  },
  {
    slug: 'how-to-make-passport-photo-at-home',
    title: 'Standard Passport & Exam ID Photo Dimensions Guide',
    excerpt: 'Create compliant 2x2 inch (51x51mm) and 35x45mm passport photos with pure white backgrounds and printable grid sheets at home.',
    category: 'How-To Guides',
    author: 'Photography & Media Specialist',
    publishedDate: 'January 2026',
    readTimeMinutes: 4,
    tags: ['Passport Photo', 'ID Card', 'Visa', 'Photo Maker', 'Print'],
    relatedToolId: 'passport-photo-maker',
    content: [
      {
        sectionId: 'standards',
        heading: '1. International Passport & Exam Photo Requirements',
        body: 'Standard US and university application photos require a 2x2 inch square format (600x600 px at 300 DPI) with head height occupying 50% to 69% of the frame. European and Asian exam portals commonly use 35x45 mm dimensions.',
      },
      {
        sectionId: 'lighting-background',
        heading: '2. Proper Lighting and Neutral Backgrounds',
        body: 'Ensure even front lighting without harsh facial shadows. Neutral backgrounds should be replaced with crisp solid white or official academic blue tones before printing on standard 4x6 inch photo paper sheets.',
      },
    ],
    faqs: [
      { question: 'Can I print multiple passport photos on one sheet?', answer: 'Yes! Using STUDKIT Passport Photo Maker, you can tile 4, 6, or 8 photos onto a single 4x6 inch layout ready for print.' },
    ],
  },
  {
    slug: 'how-to-calculate-safe-attendance-bunks',
    title: 'How to Maintain 75% Attendance and Calculate Safe Class Bunks',
    excerpt: 'Mathematically determine how many classes you can skip or must attend to meet mandatory 75% or 80% university eligibility rules.',
    category: 'Student Productivity',
    author: 'Student Life Advisory',
    publishedDate: 'January 2026',
    readTimeMinutes: 4,
    tags: ['Attendance', 'Bunk', 'College Life', 'Calculators', 'Eligibility'],
    relatedToolId: 'attendance-calculator',
    content: [
      {
        sectionId: 'attendance-formula',
        heading: '1. The 75% Attendance Equation',
        body: 'If you have attended A classes out of T total conducted classes:\nAttendance % = (A / T) × 100\n\nTo find safe bunks while maintaining minimum target P% (e.g. 75%):\nSafe Bunks = floor((100 × A - P × T) / P)',
      },
      {
        sectionId: 'recovery',
        heading: '2. How to Recover from an Attendance Shortage',
        body: 'If your current percentage is below 75%, calculate the consecutive upcoming lectures you must attend without missing a single class:\nClasses Needed = ceil((P × T - 100 × A) / (100 - P))',
      },
    ],
    faqs: [
      { question: 'Why is 75% attendance mandatory in many colleges?', answer: 'Regulatory boards mandate minimum lecture attendance to ensure course eligibility and internal assessment qualification.' },
    ],
  },
];
